add_newline = false
#format = "[_vyndlar](bold red)@$directory"
format = "($python)$directory[$character](green)"
right_format = "$git_branch$time"

[character]
success_symbol = "❯"
error_symbol = "❯(bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
#format = "on [$branch]($style) "
format = '[$symbol$branch(:$remote_branch)]($style) '


[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%T'

[python]
disabled = false
format = "$virtualenv"

